import { Store, generateHash } from './Store';
import { GitEngine } from './GitEngine';
import { Issue, PullRequest, Commit, FileChange, Member } from '../models/types';

const ISSUE_TITLES = [
  'Memory leakage during heavy image processing pipeline',
  'Optimize bundle size with code-splitting in routing modules',
  'Database query execution slow due to missing composite indexing',
  'Cross-Origin Resource Sharing (CORS) policy blocking CDN assets',
  'API route /api/users/profile crashes on empty profile parameters',
  'Setup automated database backup script to run nightly'
];

const ISSUE_DESCRIPTIONS = [
  'Users report browser lag when uploading multiple high-res pictures. Heap snapshot shows canvas elements are not garbage collected.',
  'Webpack bundle size exceeded warning: initial chunk size is 4.2MB. Need to implement React.lazy load routines.',
  'Running a query on active user logins takes 3500ms when table size exceeds 10k items. Explain analysis shows a full table scan is performed.',
  'CORS headers are missing from S3 CDN uploads, resulting in failed fetch requests from subdomains. Standard origin setup needed.',
  'Null pointer reference exception occurs in user controller when querying profiles without a profile picture URL.',
  'We need a cron service that dumps mongo tables, zips the assets, and moves them securely to AWS S3 storage.'
];

const BOTS: Member[] = [
  { id: 'alice-coder', username: 'alice-coder', avatarUrl: 'https://api.dicebear.com/7.x/adventurer/svg?seed=alice', role: 'bot' },
  { id: 'bob-reviewer', username: 'bob-reviewer', avatarUrl: 'https://api.dicebear.com/7.x/adventurer/svg?seed=bob', role: 'bot' },
  { id: 'clara-automator', username: 'clara-automator', avatarUrl: 'https://api.dicebear.com/7.x/adventurer/svg?seed=clara', role: 'bot' }
];

class BotSimulatorService {
  private selectRandomBot(): Member {
    const idx = Math.floor(Math.random() * BOTS.length);
    return BOTS[idx];
  }

  /**
   * Simulates a bot opening an issue.
   */
  public simulateOpenIssue(repoId: string): Issue {
    const bot = this.selectRandomBot();
    const idx = Math.floor(Math.random() * ISSUE_TITLES.length);
    const title = ISSUE_TITLES[idx];
    const description = ISSUE_DESCRIPTIONS[idx];

    const priorities: Issue['priority'][] = ['low', 'medium', 'high'];
    const priority = priorities[Math.floor(Math.random() * priorities.length)];

    const labelsOptions = [['bug'], ['enhancement'], ['refactor'], ['bug', 'performance'], ['documentation']];
    const labels = labelsOptions[Math.floor(Math.random() * labelsOptions.length)];

    const newIssue: Issue = {
      id: 'iss-' + Math.random().toString(36).substr(2, 9),
      repoId,
      title,
      description,
      status: 'todo',
      priority,
      assignees: [bot.username],
      labels,
      comments: [],
      createdAt: new Date().toISOString()
    };

    Store.saveIssue(newIssue);
    Store.createActivity(repoId, 'issue_open', `opened issue: "${title}"`, bot.username);

    return newIssue;
  }

  /**
   * Simulates a bot pushing a commit directly to a branch.
   */
  public simulatePushCommit(repoId: string, branchName: string): Commit {
    const bot = this.selectRandomBot();
    const branch = Store.getBranch(repoId, branchName);
    if (!branch) {
      throw new Error(`Branch ${branchName} not found`);
    }

    const messages = [
      'docs: add API documentation parameters to README',
      'refactor: optimize socket cleanup callbacks',
      'test: verify database pool reconnection logic',
      'chore: update project dependencies versions',
      'fix: handle empty arrays in payload lists'
    ];
    const message = messages[Math.floor(Math.random() * messages.length)];

    // Fetch head commit to modify some file content
    let files: FileChange[] = [];
    if (branch.headCommitHash) {
      const commit = Store.getCommit(repoId, branch.headCommitHash);
      if (commit && commit.filesChanged.length > 0) {
        // Edit an existing file
        const f = commit.filesChanged[0];
        files = [{
          filename: f.filename,
          status: 'modified',
          additions: 3,
          deletions: 1,
          content: f.content + `\n// Bot update pushed by ${bot.username} at ${new Date().toLocaleTimeString()}\n`
        }];
      }
    }

    if (files.length === 0) {
      files = [{
        filename: 'bot-updates.txt',
        status: 'added',
        additions: 5,
        deletions: 0,
        content: `Log generated by bot activity\nUser: ${bot.username}\nTime: ${new Date().toISOString()}\n`
      }];
    }

    return GitEngine.commit(repoId, branchName, message, bot.username, files);
  }

  /**
   * Simulates a bot reviewing a Pull Request.
   */
  public simulateReviewPR(repoId: string, prId: string): PullRequest {
    const pr = Store.getPullRequest(prId);
    if (!pr || pr.status !== 'open') {
      throw new Error('PR not found or not in open state');
    }

    const bot = BOTS.find(b => b.id === 'bob-reviewer') || this.selectRandomBot();
    
    // Choose status based on branch name or random chance
    // Let's make it request changes if the PR title mentions something or randomly 30% of the time.
    const mustRequestChanges = pr.title.toLowerCase().includes('database') || Math.random() < 0.35;
    
    if (mustRequestChanges) {
      const comments = [
        'Could we wrap this database lookup in a try-catch block? If connection fails, the server will crash.',
        'Looks good overall, but we need to check if inputs are sanitized before database insertion.',
        'Please add a unit test coverage to ensure null parameters do not trigger runtime errors.'
      ];
      const commentText = comments[Math.floor(Math.random() * comments.length)];

      pr.reviews.push({
        author: bot.username,
        status: 'changes_requested',
        body: 'I have left some comments regarding connection handling and payload validation.',
        createdAt: new Date().toISOString()
      });

      pr.comments.push({
        id: 'c-' + Math.random().toString(36).substr(2, 9),
        author: bot.username,
        body: commentText,
        filename: pr.sourceBranch === 'feature/auth' ? 'auth.ts' : undefined,
        line: 5,
        createdAt: new Date().toISOString()
      });

      Store.savePullRequest(pr);
      Store.createActivity(repoId, 'pr_review', `requested changes on pull request #${pr.id.replace('pr-', '')}`, bot.username);
    } else {
      pr.reviews.push({
        author: bot.username,
        status: 'approved',
        body: 'Code looks clean. Verified structure, performance optimization guidelines are met. Good to merge.',
        createdAt: new Date().toISOString()
      });

      Store.savePullRequest(pr);
      Store.createActivity(repoId, 'pr_review', `approved pull request #${pr.id.replace('pr-', '')}`, bot.username);
    }

    return pr;
  }

  /**
   * Triggers a simulated Git conflict scenario between a new branch and main.
   */
  public triggerConflictScenario(repoId: string): PullRequest {
    const mainBranch = Store.getBranch(repoId, 'main');
    if (!mainBranch) {
      throw new Error('main branch not found');
    }

    const bot = BOTS.find(b => b.id === 'alice-coder') || this.selectRandomBot();
    const conflictBranchName = `bugfix/config-clash-${Math.floor(Math.random() * 1000)}`;

    // 1. Create a branch pointing to main's head
    const sourceBranch = GitEngine.createBranch(repoId, 'main', conflictBranchName);

    // 2. Commit a change on the main branch modifying line 5 of server.ts
    const originalServerCommit = Store.getCommit(repoId, mainBranch.headCommitHash);
    let originalServerContent = 'import express from "express";\nconst app = express();\napp.use(express.json());\napp.get("/", (req, res) => {\n  res.send("Server running!");\n});\napp.listen(3000, () => console.log("Server listening"));\n';
    
    if (originalServerCommit) {
      const serverFile = originalServerCommit.filesChanged.find(f => f.filename === 'server.ts');
      if (serverFile) {
        originalServerContent = serverFile.content;
      }
    }

    // Modify file on main branch
    const mainContent = originalServerContent.replace(
      'res.send("Server running!");',
      'res.send("Welcome to GitForge main server portal!"); // Main update'
    );
    GitEngine.commit(
      repoId,
      'main',
      'chore: update landing page index route message on main',
      'you',
      [{ filename: 'server.ts', status: 'modified', additions: 1, deletions: 1, content: mainContent }]
    );

    // 3. Commit a different change on the conflict branch modifying line 5 of server.ts
    const branchContent = originalServerContent.replace(
      'res.send("Server running!");',
      'res.send("Bot collaborator test route online!"); // Branch update'
    );
    GitEngine.commit(
      repoId,
      conflictBranchName,
      'fix: customize welcome payload string for API validation',
      bot.username,
      [{ filename: 'server.ts', status: 'modified', additions: 1, deletions: 1, content: branchContent }]
    );

    // 4. Open PR
    const prNumber = Store.getPullRequests(repoId).length + 1;
    const prId = `pr-${prNumber}`;
    const newPR: PullRequest = {
      id: prId,
      repoId,
      title: `fix: improve backend router greeting messaging`,
      description: `A bot-driven change to update greetings. NOTE: Both this branch and main modify server.ts, causing a conflict.`,
      sourceBranch: conflictBranchName,
      targetBranch: 'main',
      status: 'open',
      author: bot.username,
      comments: [
        {
          id: 'c-' + Math.random().toString(36).substr(2, 9),
          author: 'clara-automator',
          body: 'Automated CI build status: warning. Direct line modifications detected on server.ts. Merge conflict flagged.',
          createdAt: new Date().toISOString()
        }
      ],
      reviews: [],
      createdAt: new Date().toISOString()
    };

    Store.savePullRequest(newPR);
    Store.createActivity(repoId, 'pr_open', `opened pull request #${prNumber} causing conflict: "${newPR.title}"`, bot.username);

    return newPR;
  }
}

export const BotService = new BotSimulatorService();
